apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: mycluster
servers: 1
agents: 1
image: rancher/k3s:v1.29.1-k3s1

# 1. Recursos de Hardware (Aumentados para o GitLab)
options:
  runtime:
    labels:
      - label: "role=control-plane"
        nodeFilters: [server:0]
      - label: "role=worker"
        nodeFilters: [agent:0]

# Mapeamento de portas para o Traefik (essencial para o Ingress)
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
  - port: 5432:5432
    nodeFilters:
      - loadbalancer
  - port: 25:25
    nodeFilters:
      - loadbalancer
  - port: 465:465
    nodeFilters:
      - loadbalancer
  - port: 587:587
    nodeFilters:
      - loadbalancer
  - port: 993:993
    nodeFilters:
      - loadbalancer

# 2. Configuração do Kubelet e Recursos
registries:
  config: |
    mirrors:
      "registry.avocadotech.site":
        endpoint:
          - "http://gitlab-registry.gitlab.svc.cluster.local:5000"
kubeAPI:
  host: "127.0.0.1"
  hostIP: "127.0.0.1"
  hostPort: "6443"

# Pods e Recursos
k3s:
  extraArgs:
    - arg: "--kubelet-arg=max-pods=110"
      nodeFilters: [server:0, agent:0]
    - arg: "--node-taint=CriticalAddonsOnly=true:NoExecute"
      nodeFilters: [server:0]

# 3. Limites de Memória e CPU via Docker
env:
  - envVar: K3D_SERVER_MEMORY=3G
    nodeFilters: [server:0]
  - envVar: K3D_AGENT_MEMORY=6G
    nodeFilters: [agent:0]
