apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik-host-ingress
  namespace: authentik
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/ingress.provider: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "false"
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - authentik.avocado.tail799250.ts.net
      secretName: tailscale-certs
  rules:
    - host: authentik.avocado.tail799250.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authentik-server
                port:
                  number: 9000
