apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-host-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - host: minio.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9001
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9000
          - path: /minio
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9000
