apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-host-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - minio.avocadotech.site
        - minio-console.avocadotech.site
      secretName: nginx-certs # Usa o certificado wildcard já emitido
  rules:
    - host: minio.avocadotech.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9000
    - host: minio-console.avocadotech.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9001
