apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres-hostpath
  labels:
    app: postgres
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/home/beto/Área de trabalho/Docs/docker imagens/postgresql/data"
    type: DirectoryOrCreate

