apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: default
stringData:
  accesskey: "minioadmin"
  secretkey: "minioadmin"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: default
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-credentials
  namespace: default
stringData:
  KC_DB_USERNAME: "keycloak"
  KC_DB_PASSWORD: "keycloak"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: default
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "123456"

