auth:
  existingSecret: minio-credentials

service:
  type: ClusterIP

defaultBuckets:
  - terraform-state
  - gitlab-lfs
  - gitlab-artifacts
  - gitlab-uploads
  - gitlab-packages

ingress:
  enabled: true
  ingressClassName: traefik
  hostname: minio.${domain_name}
  path: /

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m

persistence:
  enabled: true
  size: 10Gi