apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres-hostpath
  labels:
    app: postgres
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    # Replace this path if you want to manage the PV manifest manually.
    path: "/path/to/repo/volume/postgres"
    type: DirectoryOrCreate
