apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stalwart.fullname" . }}-env
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.recoveryAdmin.enabled }}
  STALWART_RECOVERY_ADMIN: {{ printf "%s:%s" .Values.recoveryAdmin.username .Values.recoveryAdmin.password | quote }}
  {{- end }}
  {{- if .Values.role }}
  STALWART_ROLE: {{ .Values.role | quote }}
  {{- end }}
  {{- if .Values.pushShard }}
  STALWART_PUSH_SHARD: {{ .Values.pushShard | quote }}
  {{- end }}
  STALWART_RECOVERY_MODE: {{ .Values.recoveryMode.enabled | quote }}
  STALWART_RECOVERY_MODE_PORT: {{ .Values.recoveryMode.port | quote }}
  STALWART_RECOVERY_MODE_LOG_LEVEL: {{ .Values.recoveryMode.logLevel | quote }}
  {{- range $key, $value := .Values.extraSecretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
